server:
  port: 8089

spring:
  application:
    name: audit-server
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_server
    username: postgres
    password: Welcome@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
